### ISSUE TITLE
프론트엔드 서버와 백엔드 서버 통신

### ISSUE THREAD

**Issue by bhj8551** [kdt-programmers-b6/MeowBowWow2emoji#10]
vue.js로 만든 프론트엔드 서버와 django로 만든 백엔드 서버가 통신할 수 있게 만들자.

**Comment by bhj8551** [comment]
연결 시도 방법 2가지 중 하나인 Vue를 build해서 모듈처럼 장고에서 사용하는 벙법은 실패
vue.js로 만든 프론트엔드 서버와 django로 만든 백엔드 서버가 따로 통신하는 방법을 사용

**Comment by HyunWooZZ** [comment]
해당 사항 구현 완료
