### ISSUE TITLE
데이터 추가 정제 작업

### ISSUE THREAD

**Issue by bhj8551** [kdt-programmers-b6/MeowBowWow2emoji#13]
현재 학습하고 있는 모델은 그대로 학습시키고
데이터를 추가로 정제해서 학습시켜서 비교를 해보자!

그러기 위해서는 현재 데이터에서 추가로 정제가 필요하다.
정제 규칙에 따라 주말동안 열심히 정제하자!

Read me를 읽고 작업

**Comment by bhj8551** [comment]
작업 완료 👍 
참고 사항 : 얼굴이 형태가 너무 이상하거나 고양이 같지 않은 이미지를 삭제함

**Comment by HyunWooZZ** [comment]
작업 완료 👍
참고 사항 : 얼굴이 형태가 너무 이상하거나 고양이 같지 않은 이미지를 삭제함
개수 : 600 -> 271
