### ISSUE TITLE
2차 전처리 데이터로 U-GAT-IT tf모델 고양이 모델 학습

### ISSUE THREAD

**Issue by bhj8551** [kdt-programmers-b6/MeowBowWow2emoji#19]
주말동안 고양이 얼굴 위주로 다시 전처리한 데이터를 가지고
U-GAT-IT tf모델 고양이 모델 학습을 시도해보자 (일단은 10~20에포크 진행 후 결과 확인)

**Comment by bhj8551** [comment]
pretrain된 light 버전도 같이 학습 진행 중 (비교 대상)

**Comment by ddddjjjj** [comment]
pretrained light 10epoch로 설정 후 진행 중 - 새벽에 train끝날 것으로 예상
not pretrained 처음부터 100epoch 진행 중 - 목요일 멘토링 전까지 끝날 수 있을지 의문
