### ISSUE TITLE
Vue 기본 템플릿에서 파일 업로드, 이미지 출력 관련 기능 공부 및 구현

### ISSUE THREAD

**Issue by bhj8551** [kdt-programmers-b6/MeowBowWow2emoji#29]
Vue 기본 템플릿에서 파일 업로드, 이미지 출력 관련 기능 공부 및 구현해서 프로토타입 내보기

**Comment by HyunWooZZ** [comment]
체크 박스로 고양이인지 개인지 확인할 수 있게 만들기

**Comment by HyunWooZZ** [comment]
https://george-hadjigeorgiou97.medium.com/step-by-step-custom-drag-drop-upload-component-in-vuetify-vue-2-43c99794643d  > hugging face ui 만들 때 참조할 것

https://vuetifyjs.com/en/components/checkboxes/#colors > checkbox 만들 때 바인딩 하는 법 참고할 docs

**Comment by HyunWooZZ** [comment]
이미지 가운데로 정렬 및 기본적인 레이아웃 정리

**Comment by HyunWooZZ** [comment]
이미지 파일을 2개 올려 놓는데 원본 이미지를 기본으로 하되 마우스를 올리면 이미지가 변환되게 구현해야함 .
해당 이슈는 정희님이 도와주실 예정

오늘은 드래그앤 드랍 기능 구현하기

**Comment by HyunWooZZ** [comment]
고양이 강아지 체크박스 v1, v2 구현

**Comment by HyunWooZZ** [comment]
예시 이미지 호버 기능 구현하기 + v1 v2 체크 박스 구현해야함.

**Comment by HyunWooZZ** [comment]
모든 기능 구현 완료.
