### ISSUE TITLE
데이터 정제 가이드라인 만들기 ( 멘토링 후 결정 )

### ISSUE THREAD

**Issue by bhj8551** [kdt-programmers-b6/MeowBowWow2emoji#31]
멘토링 후 앞으로의 서비스 방향에 대해 결정 후 가이드라인 만들기

**Comment by ddddjjjj** [comment]
![diagram-export-2022  4  22  오후 4_40_19](https://user-images.githubusercontent.com/43689301/164648827-becb8329-a814-49bd-bb92-ec2aa04a7650.svg)

모델 학습 결과가 좋지 않아 데이터를 더 정제해야겠다고 판단함.
이모티콘의 그림체가 다양하기 때문에 이모티콘을 비슷한 그림체끼리 나누기로함
그림체가 간단한지 복잡한지를 기준으로 상, 중, 하로 나누고 특이한 그림체는 삭제하기로 정함
각자 할당받은 이모티콘을 분류 기준에 따라 나누고 얼굴을 crop해서 모델 훈련을 다시 시작할 계획
crop작업은 알씨 프로그램을 사용하고 얼굴이 많이 기울어져 있거나 가려져 있으면 삭제
crop한 후 256*256사이즈로 resize하는 작업이 있기 때문에 crop진행 시 얼굴 이미지의 비율, 크기를 고려할 것

#### 데이터가 부족할 것 같다는 의견

**Comment by lyeong-gwa** [comment]
crop할 때 불필요한 부분을 지워야 하는지 그냥 둬도 되는지 궁금함 
ex)
원본
![8570](https://user-images.githubusercontent.com/75747197/164972296-784644f0-afbf-435f-95d8-c2ba142cf2b1.png)

1.crop결과 (얼굴부분 추출)
![8570](https://user-images.githubusercontent.com/75747197/164972314-42bc71cc-8939-4dc3-be81-03a2f79b68a3.png)

2.crop결과 (얼굴부분 추출 + 불필요한 부분제거)
![8570](https://user-images.githubusercontent.com/75747197/164972349-1c43a102-1552-44a0-9b06-ce56931d5558.png)

1번인지 2번인지 기억이 가물함.
