### ISSUE TITLE
홈페이지 메인 title 정하기

### ISSUE THREAD

**Issue by HyunWooZZ** [kdt-programmers-b6/MeowBowWow2emoji#34]
홈페이지에 예쁘게 나올 수 있는 타이틀 및 아이콘을 등록해야 합니다!
댓글 Form Example
팀 이름: 멍멍야옹야옹
프로젝트 이름: mewbow2emoji
홈페이지 제목: 개를 이모티콘으로 바꾼다.

확인하시고 꼭 댓글을 달아주세요

**Comment by lyeong-gwa** [comment]
팀 이름: 개파냥파 (개 vs 냥)
우파루파 영상보다 생각났습니다...ㅋㅋ

프로젝트 이름: mewbow2emoji (이대로 가도 상관없을거 같습니다....?)


홈페이지 제목: 개, 고양이 이모지 변환
홈페이지 제목을 보고 어떤 홈페이지인지 알아야 된다고 생각했습니다.

**Comment by HyunWooZZ** [comment]
팀 이름: 귀여운 걸로 만들어주지
프로젝트 이름: mewbow2emoji
홈페이지 제목: 이모지로 바꾼다냥!

**Comment by Do-Ray** [comment]
팀이름 : 이게 멍냥 / 멍냥이모지 ? 
프로젝트 이름 : mewbow2emoji 
홈페이지 제목 : Pet to Emo

**Comment by ddddjjjj** [comment]
팀 이름: 멍멍야옹
프로젝트 이름: dogcat2emoji
홈페이지 제목: We'll draw your dog or cat

**Comment by bhj8551** [comment]
팀 이름: ???
프로젝트 이름: catdog2emoji
홈페이지 제목: transfer the cat to the emoji with GAN
