### ISSUE TITLE
훈련 데이터 적재

### ISSUE THREAD

**Issue by bhj8551** [kdt-programmers-b6/MeowBowWow2emoji#4]
팀 공유 드라이버에 선별된 훈련 데이터를 저장하기

폴더 경로와 이름을 적어주세요

**Comment by ddddjjjj** [comment]
dir = '/content/drive/Shareddrives/[3-B]shared Drive/ugatit/UGATIT-tf/dataset'
dir 안에 doggie2emoji, kittie2emoji입니다.
각각 강아지, 고양이 데이터입니다.
