### ISSUE TITLE
Vue.js 공부 후 간단한 프로토타입 만들어 보기

### ISSUE THREAD

**Issue by bhj8551** [kdt-programmers-b6/MeowBowWow2emoji#6]
Vue.js를 공부 후 간단한 프로토타입을 만들어 보자.
기왕이면 우리 프로젝트에 사용될 만한 예시면 더 좋다.

**Comment by HyunWooZZ** [comment]
base line 코드는 올려 놓았으나, 경로 설정이 하드 코딩되어 있어서 아직 보완할 점이 많이 존재합니다.
 현재 문제점은 경로 설정등을 상대적으로 지정을 잘했음에도 불구하고 뷰가 인식을 못해서 어려움을 겪고 있고,
template 구성을 제가 완전히 소스코드를 보고 완전히 커스터마이징 하는 경우라 시간과 노력이 조금 많이 걸릴 것 같습니다.
template 구성시 현재 문제점은 2가지가 존재합니다. 
1. 기존 bootstrap 코드를 객체지향적으로 설계하기 위해 폴더 구조를 어떻게 정해야 할지 조금 난감합니다.
2. 기존 bootstrap 코드는 이해하겠는데 이러한 코드들을 vue 식으로 표현하기가 조금 난해한 것 같습니다.

**Comment by HyunWooZZ** [comment]
vue cli 를 이용해 간단한 프로토타입을 만들어 보았습니다.
![image](https://user-images.githubusercontent.com/92921909/163958563-a9256dc3-17c0-4285-8821-c76369ce551a.png)
