### ISSUE TITLE
U-GAT-IT tensorflow 모델 훈련 시 버그 픽스

### ISSUE THREAD

**Issue by bhj8551** [kdt-programmers-b6/MeowBowWow2emoji#7]
U-GAT-IT tensorflow pretrain 모델 학습 시 out of memory 에러가 발생한다.

**Comment by ddddjjjj** [comment]
parser argument중에 --ch 값을 64->16으로 낮추었더니 해결됐습니다.
adalin 계산할 때 layer를 말하는 것 같은데 어떤 값인지 잘 모르겠어서 논문을 봐야겠습니다.

**Comment by ddddjjjj** [comment]
### 현재까지 알게된 사실

1. https://github.com/taki0112/UGATIT에 올라와 있는 checkpoint파일(--light False)은 mac 아카이브 유틸리티로 파일 압축을 풀 때만 정상적으로 압축이 풀린다.(논문 저자 github issue에 써있고 내가 다른 여러가지 방법으로 실행했을 때 train시 오류가 생김)

2. train시 --ch 64(default)로 설정하고 pretrained model을 불러오면 colab pro, colab pro plus모두에서 에러(gpu ram out of momory)
 
3. train시 --ch 값을 바꾸면 체크포인트를 불러오는 것까지 성공하지만 이후 트레인에서 lhs, rhs값이 다르다고 오류

4. 현재 pretrained model없이 트레인을 하고 있지만 며칠이 걸릴 것으로 예상

5. 모델의 light모드 pretrained model을 캐글에서 찾아서 --epoch 30으로 설정하고 현재 train 진행 중. 이와 별개로 1시간 내로 pretrained model + 1epoch train이 끝날 예정

6. aws 인스턴스를 바꿔야 train이 정상적으로 할 것 같음. minimun p2 xlarge -> gpu ram 16기가
