### ISSUE TITLE
묵업 ui, ux 디자인하기

### ISSUE THREAD

**Issue by bhj8551** [kdt-programmers-b6/MeowBowWow2emoji#9]
프로토타입 서비스를 위한 묵업 ui, ux 디자인하기
부트스트랩을 가져와서 커스터마이징 하는 방향

**Comment by HyunWooZZ** [comment]
[기본ui.pdf](https://github.com/kdt-programmers-b6/MeowBowWow2emoji/files/8478854/ui.pdf)

해당 파일 공유 드라이브에도 올려 놓았습니다.
